// Sahara Groceries — catalog seed data. Mirrors the client mock for visual consistency.
const img = (id, w = 1200) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const RICE = [
  'photo-1586201375761-83865001e31c',
  'photo-1536304929831-ee1ca9d44906',
  'photo-1626202373052-9cdb09e9c3c1',
  'photo-1568347355280-d33fdf77d42a',
  'photo-1596797038530-2c107229654b',
  'photo-1574323347407-f5e1c0cf4b46',
];
const SPICES = [
  'photo-1532336414038-cf19250c5757',
  'photo-1599909533734-fb6e3a3aafe8',
  'photo-1505253716362-afaea1d3d1af',
  'photo-1596040033229-a9821ebd058d',
  'photo-1542990253-0d0f5be5f0ed',
];
const PANTRY = [
  'photo-1474979266404-7eaacbcd87c5',
  'photo-1517457373958-b7bdd4587205',
  'photo-1601493700631-2b16ec4b4716',
  'photo-1604908176997-125f25cc6f3d',
  'photo-1542838132-92c53300491e',
];
const LEGUMES = [
  'photo-1614961233913-a5113a4a34ed',
  'photo-1515543904379-3d757afe72e4',
  'photo-1593251696073-5d1ad8f01b97',
];

export const categoriesData = [
  { slug: 'rice', name: 'Rice', image: img(RICE[0]), order: 1 },
  { slug: 'grains', name: 'Grains', image: img(LEGUMES[1]), order: 2 },
  { slug: 'spices', name: 'Spices', image: img(SPICES[0]), order: 3 },
  { slug: 'pantry', name: 'Pantry', image: img(PANTRY[3]), order: 4 },
  { slug: 'deals', name: 'Deals', image: img(SPICES[1]), order: 5 },
];

export const productsData = [
  {
    slug: 'royal-basmati-rice', name: 'Royal Basmati',
    brand: 'India', categorySlug: 'rice', price: 2499, compareAt: 2850,
    isBestSeller: true, isFeatured: true,
    images: [img(RICE[0]), img(RICE[2]), img(RICE[1]), img(RICE[3])],
    description: 'Aged for two years for peak aroma and exceptional grain length. Hand-graded from the Himalayan foothills, each kernel separates beautifully and triples in length when cooked.',
    variants: [
      { sku: 'RB-5KG', label: '5 kg bag', stock: 9 },
      { sku: 'RB-10KG', label: '10 kg sack', stock: 5, priceDelta: 1800 },
    ],
    tags: ['long grain', 'aged', 'aromatic'],
    badges: ['Aged 2 Years', 'Best Seller'],
    soldCount: 1842,
  },
  {
    slug: 'fragrant-jasmine-rice', name: 'Fragrant Jasmine',
    brand: 'Thailand', categorySlug: 'rice', price: 1950,
    isBestSeller: true, isFeatured: true,
    images: [img(RICE[3]), img(RICE[4]), img(RICE[0])],
    description: 'Aromatic, slightly sticky texture from the rice fields of Thailand. Perfect for stir-fries, curries, and steamed sides. Sealed at source for freshness.',
    variants: [{ sku: 'JS-5KG', label: '5 kg bag', stock: 22 }],
    tags: ['long grain', 'aromatic'],
    soldCount: 1204,
  },
  {
    slug: 'arborio-superiore', name: 'Arborio Superiore',
    brand: 'Italy', categorySlug: 'rice', price: 1400,
    isFeatured: true,
    images: [img(RICE[1]), img(RICE[5])],
    description: 'Plump, starchy short-grain rice from the Po Valley. Absorbs broth without losing bite — the only rice that makes a true risotto alla Milanese.',
    variants: [{ sku: 'AR-2KG', label: '2 kg bag', stock: 18 }],
    tags: ['short grain', 'risotto'],
    soldCount: 612,
  },
  {
    slug: 'brown-basmati-rice', name: 'Brown Basmati',
    brand: 'India', categorySlug: 'rice', price: 2600,
    images: [img(RICE[1]), img(RICE[0])],
    description: 'Nutty, whole-grain basmati with the bran intact. Higher fibre, lower glycaemic index — and still that signature long-grain fluff.',
    variants: [{ sku: 'BB-5KG', label: '5 kg bag', stock: 11 }],
    tags: ['whole grain', 'long grain'],
    soldCount: 388,
  },
  {
    slug: 'persian-saffron-threads', name: 'Persian Saffron Threads',
    brand: 'Iran', categorySlug: 'spices', price: 4500, compareAt: 5500,
    isBestSeller: true, isFeatured: true,
    images: [img(SPICES[1]), img(SPICES[0]), img(SPICES[2])],
    description: 'Coupe-grade Persian saffron, the highest quality available. Hand-harvested filaments deliver intense colour, honeyed aroma, and the unmistakable depth of true saffron.',
    variants: [
      { sku: 'SAF-2G', label: '2 grams', stock: 18 },
      { sku: 'SAF-5G', label: '5 grams', stock: 10, priceDelta: 6500 },
    ],
    tags: ['premium', 'sun-dried'],
    badges: ['Premium Grade', 'Limited'],
    soldCount: 2310,
  },
  {
    slug: 'green-cardamom-pods', name: 'Green Cardamom Pods',
    brand: 'India', categorySlug: 'spices', price: 900,
    isFeatured: true,
    images: [img(SPICES[3]), img(SPICES[0])],
    description: 'Whole, single-origin pods from Kerala. Floral, sweet, intensely aromatic — crush gently and add to chai, biryanis, and pilafs.',
    variants: [{ sku: 'CDM-50G', label: '50 g jar', stock: 40 }],
    tags: ['whole spice', 'single origin'],
    soldCount: 524,
  },
  {
    slug: 'cultured-ghee', name: 'Cultured Ghee',
    brand: 'India', categorySlug: 'pantry', price: 1450,
    isBestSeller: true,
    images: [img(PANTRY[2]), img(PANTRY[3])],
    description: 'Slow-simmered grass-fed butter, cultured for 12 hours before clarifying. Nutty, golden, with a high smoke point ideal for everyday cooking.',
    variants: [{ sku: 'GHE-470', label: '470 ml jar', stock: 24 }],
    tags: ['grass-fed', 'traditional'],
    soldCount: 1098,
  },
  {
    slug: 'pink-himalayan-salt', name: 'Pink Himalayan Salt',
    brand: 'India', categorySlug: 'pantry', price: 450,
    images: [img(PANTRY[1])],
    description: 'Coarse-ground crystals mined from the Khewra deposits. Mineral-rich and clean tasting — perfect for grinders and finishing.',
    variants: [{ sku: 'PHS-500', label: '500 g', stock: 60 }],
    tags: ['mineral', 'coarse'],
    soldCount: 740,
  },
  {
    slug: 'organic-medjool-dates', name: 'Organic Medjool Dates',
    brand: 'California', categorySlug: 'pantry', price: 1800,
    isBestSeller: true,
    images: [img(PANTRY[2]), img(PANTRY[4])],
    description: 'Plump, soft Californian Medjools with deep caramel notes. Each fruit hand-selected — naturally sweet, naturally good.',
    variants: [
      { sku: 'MDJ-1LB', label: '1 lb box', stock: 30 },
      { sku: 'MDJ-3LB', label: '3 lb gift box', stock: 12, priceDelta: 3800 },
    ],
    tags: ['organic', 'whole'],
    badges: ['USDA Organic'],
    soldCount: 956,
  },
  {
    slug: 'cold-pressed-olive-oil', name: 'Cold-Pressed Olive Oil',
    brand: 'Italy', categorySlug: 'pantry', price: 1950,
    isBestSeller: true, isFeatured: true,
    images: [img(PANTRY[0]), img(PANTRY[3])],
    description: 'First-press extra-virgin olive oil from a single Tuscan estate. Grassy, peppery finish — bottled within hours of harvest.',
    variants: [
      { sku: 'OO-500', label: '500 ml bottle', stock: 18 },
      { sku: 'OO-1L', label: '1 L tin', stock: 9, priceDelta: 1800 },
    ],
    tags: ['single estate', 'first extraction'],
    badges: ['Single Estate'],
    soldCount: 1473,
  },
  {
    slug: 'french-green-lentils', name: 'French Green Lentils',
    brand: 'Italy', categorySlug: 'grains', price: 650,
    images: [img(LEGUMES[0]), img(LEGUMES[1])],
    description: 'Du Puy-style lentils that hold their shape beautifully when cooked. Earthy, peppery, and quick-cooking — a pantry workhorse.',
    variants: [{ sku: 'FGL-500', label: '500 g', stock: 35 }],
    tags: ['lentils', 'whole'],
    soldCount: 312,
  },
  {
    slug: 'stone-ground-flour', name: 'Stone-Ground Flour',
    brand: 'Italy', categorySlug: 'grains', price: 850,
    images: [img(LEGUMES[2]), img(PANTRY[4])],
    description: 'Ancient-grain wheat, milled slowly between stone wheels to preserve the germ. Rich, nutty, and unmatched for rustic breads.',
    variants: [{ sku: 'SGF-1KG', label: '1 kg bag', stock: 22 }],
    tags: ['ancient grain', 'stone-milled'],
    soldCount: 268,
  },
  {
    slug: 'golden-sella-basmati', name: 'Golden Sella Basmati',
    brand: 'India', categorySlug: 'rice', price: 1200,
    isFeatured: true,
    images: [img(RICE[2]), img(RICE[0])],
    description: 'Parboiled to lock in nutrients, then aged. Extra-long grains stay separate and fluffy — ideal for biryani and pulao.',
    variants: [{ sku: 'GS-5KG', label: '5 kg bag', stock: 30 }],
    tags: ['parboiled', 'long grain'],
    soldCount: 489,
  },
  {
    slug: 'aged-basmati-rice', name: 'Aged Basmati Rice',
    brand: 'India', categorySlug: 'deals', price: 2850, compareAt: 3400,
    images: [img(RICE[2]), img(RICE[5])],
    description: 'Climate-aged for 18 months in our temperature-controlled silos. Deeper aroma, longer grain, and a fluffier finish than the season fresh crop.',
    variants: [{ sku: 'ABR-5KG', label: '5 kg bag', stock: 14 }],
    tags: ['aged', 'long grain'],
    badges: ['On Sale'],
    soldCount: 612,
  },
];
